### get products
get http://localhost:3000/products

### get product
get http://localhost:3000/products/2

### post product
post http://localhost:3000/products
Content-Type: application/json

{
    "id": 6,
    "name": "Áru 6",
    "price": 1500,
    "quantity": 97,
    "type": "tejtermék"
}

### delete product
delete http://localhost:3000/products/6

### put product
put http://localhost:3000/products/6
Content-Type: application/json

{
    "id": 6,
    "name": "Áru 66",
    "price": 1500,
    "quantity": 97,
    "type": "tejtermék"
}


